// read data

d3.json("data/top_artists.json").then(function(dataset){
    console.log(dataset)

    var width = 512
    var height = 500

    const layout = d3.tree().size([height, width-100]);
    var root = d3.hierarchy(dataset, d => d.children);
    layout(root);
    
    console.log(root)

    // get topArtists svg
    var svg = d3.select('#topArtists')
                .style("width", width)
                .style("height", height)

                let bound = svg.append("g")
                .attr("transform", `translate(10,0)`)
    
    let link = bound.insert("g")
                .attr("fill", "none")
                .attr("stroke", "#555")
                .attr("stroke-opacity", 0.4)
                .attr("stroke-width", 2)
                .selectAll("path")
                .data(root.links()) //TODO: here you have to pass the links generated by your hierarchy
                .join("path")
                .attr("d", d3.linkHorizontal()
                      .x(d => d.y)
                      .y(d => d.x));
    
    const node = bound.append("g")
                .selectAll("circle")
                .data(root.descendants()) //TODO: here you have to pass the descendants of your root
                .enter()
                .append("circle")
                .attr("transform", d => `translate(${d.y},${d.x})`)
                .attr("fill", d => d.children ? "#555" : "#999")
                .attr("r", 4)

    node.append("text")
        .attr("dy", ".35em")
        .attr("x", 10)
        .attr("y", 10)
        .style("text-anchor", d => d.children ? "end" : "start")
        .text(d => d.data.name);

})